### ISSUE TITLE
Can't see full text

### ISSUE THREAD

**Issue by danieljwilson** [JuneOh710/jdm-classics#2]
On the screen with the question about a jar with colored marbles the text is getting cut off. 

Can you please make sure that it scrolls if the whole thing can't fit on screen?

This is what I am seeing now even if I try and scroll all the way up:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/7377893/157838055-5d06392c-da31-40a6-b9ca-fe8a0bb0f4c8.png">

**Comment by JuneOh710** [comment]
I can't replicate this issue. I made some style changes that could solve this.
